[package]
name = "bevy-bobox-examples"
version = "0.8.0"
edition = "2021"
homepage = "https://github.com/Bobox214/bevy-bobox-examples"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
license = "MIT or Apache-2.0"
rust-version = "1.62"

[dependencies]
bevy = "0.8"